-- One-time backfill of the real portfolio content that used to live in
-- the old Supabase Postgres, carried over during the Supabase -> self-hosted
-- Go/Postgres/MinIO migration. Goose tracks this as already-applied after
-- its first run, so it's a safe no-op on every boot after that — including
-- against a database where this content has since been edited via /admin
-- (ON CONFLICT DO NOTHING everywhere, so it never overwrites live edits).
--
-- avatar_url, resume_url, and the post's cover_image_url were deliberately
-- left NULL here rather than carried over: the source values pointed at the
-- old Supabase Storage bucket, which nothing in this project reads from
-- anymore. Re-upload those three files once through /admin after this runs.
--
-- +goose Up
INSERT INTO public.education (id, institution, degree, field, start_date, end_date, gpa, location, description, achievements, relevant_coursework, thesis, sort_order) VALUES ('sos-plus2', 'SOS Hermann Gmeiner School, Sanothimi, Bhaktapur, Nepal', '+2 Science', 'Physics and Mathematics', '2019', '2021', 'A+', 'Sanothimi, Bhaktapur, Nepal', 'Higher secondary education with strong foundation in science and mathematics. Grade 11: Physics, Chemistry, Mathematics, English, Biology (Minor). Grade 12: Physics, Chemistry, Mathematics (Major), English, Nepali.', '{"Achieved Grade A+","Bestmanship Awardee 2019","Music Club President"}', '{}', NULL, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.education (id, institution, degree, field, start_date, end_date, gpa, location, description, achievements, relevant_coursework, thesis, sort_order) VALUES ('ioe-bachelor', 'Tribhuvan University, IOE, Pulchowk Campus', 'Bachelor of Engineering (B.E.)', 'Electronics, Communication and Information Engineering', '2021-05', '2026-05', '75%', 'Pulchowk Campus, Lalitpur, Nepal', 'Comprehensive engineering program with focus on electronics, communication systems, information theory, and signal processing. Strong foundation in mathematics, algorithms, and systems design.', '{"Active member of IEEE Student Branch (Chair 2023-2024)","Creative Director at IEEE Pulchowk Student Branch","Executive Committee Member at Pulchowk Music Club"}', '{"Data Structures & Algorithms","Digital Signal Processing","Communication Systems","Computer Networks","Machine Learning","Operating Systems","Microprocessor Systems","Information Theory","Probability & Statistics","Network Programming"}', NULL, 0) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('ryc-global-officer', 'Officer', 'RYC Global', NULL, 'job', '2020-03', '2022-08', 'Served as an Officer at RYC Global, contributing to organizational operations and initiatives.', '{"Managed organizational operations","Coordinated with team members on various initiatives","Contributed to organizational growth and development"}', '{"Operations Management","Team Coordination"}', '{}', NULL, 0, '2026-08-16 12:22:06.52169+05:30', '2026-08-16 12:22:06.52169+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('pointzeroo-frontend', 'Frontend Developer', 'PointZeroo', 'Nepal', 'job', '2022-03', '2022-09', 'Maintained an e-commerce website and developed a web application for SSoChe, Pulchowk Campus, focusing on frontend development with modern web technologies.', '{"Maintained an e-commerce website","Developed a web application for SSoChe, Pulchowk Campus","Implemented frontend features using HTML5, CSS, and JavaScript","Worked with SQL databases for data management"}', '{JavaScript,HTML5,CSS,SQL,"Front-End Development"}', '{"Successfully maintained and enhanced e-commerce platform","Delivered web application for educational institution"}', NULL, 0, '2026-08-16 12:22:06.224011+05:30', '2026-08-16 12:22:06.224011+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('pulchowk-music', 'Executive Committee Member', 'Pulchowk Music Club And Research Center', 'Pulchowk, Lalitpur, Nepal', 'internship', '2022-05', '2023-07', 'Served as Executive Committee Member at Pulchowk Music Club And Research Center, contributing to music-related activities and events.', '{"Participated in executive committee decisions","Organized music events and activities","Contributed to club operations and management"}', '{Music,"Event Organization","Committee Management"}', '{}', NULL, 0, '2026-08-16 12:22:05.921376+05:30', '2026-08-16 12:22:05.921376+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('ieee-creative', 'Creative Director', 'IEEE Pulchowk Student Branch', 'Pulchowk', 'internship', '2023-03', '2024-05', 'Served as Creative Director for IEEE Pulchowk Student Branch, managing creative content and visual communications for the branch.', '{"Managed creative content for IEEE Pulchowk Student Branch","Designed visual communications and promotional materials","Coordinated creative initiatives and campaigns"}', '{"Creative Design","Visual Communications","Content Management"}', '{"Enhanced branch visibility through creative initiatives"}', NULL, 0, '2026-08-16 12:22:05.62407+05:30', '2026-08-16 12:22:05.62407+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('ieee-chair', 'Chair', 'IEEE Pulchowk Student Branch', 'Lalitpur District, Nepal', 'internship', '2023-04', '2024-06', 'Led IEEE Pulchowk Student Branch as Chair, organizing technical events, workshops, and coordinating student activities.', '{"Led the IEEE Pulchowk Student Branch as Chair","Organized technical events and workshops","Coordinated student activities and initiatives","Managed branch operations and member engagement"}', '{Leadership,"Event Management","Team Coordination","Technical Workshops"}', '{"Successfully led the student branch for over a year","Organized multiple technical events and workshops"}', NULL, 0, '2026-08-16 12:22:05.317724+05:30', '2026-08-16 12:22:05.317724+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('ibtidaa-fullstack', 'Full Stack Developer', 'Ibtidaa Softwares Pvt. Ltd.', 'Nepal', 'job', '2023-10', '2024-12', 'Developed and maintained full-stack applications including ''Bidesh'' App and Website for RP Srijan Way To Success using Next.js, and an Event Management and Visualization Tool using Django and JavaScript for Shramik Sanjal.', '{"Developed and maintained ''Bidesh'' App and Website using Next.js","Built Event Management and Visualization Tool using Django and JavaScript","Served as Tech Lead for development projects","Implemented data visualization features using Chart.js"}', '{Next.js,PostgreSQL,NestJS,Express.js,MongoDB,Jenkins,Redux.js,Node.js,JavaScript,React.js,"Django REST Framework",Python,Chart.js}', '{"Successfully delivered multiple full-stack applications","Led technical development as Tech Lead"}', NULL, 0, '2026-08-16 12:22:05.02251+05:30', '2026-08-16 12:22:05.02251+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('isrc-ninja-combined', 'Full Stack Engineer / Tech Lead', 'Intensive Study and Research Center (ISRC), later Ninja Infosys', 'Kathmandu, Nepal', 'job', '2024-01', '2026-02', 'Drove large-scale digital transformation across Nepal''s municipal governance ecosystem — from building survey and digital profile infrastructure for 10+ municipalities, to leading architecture for platforms serving 50+ municipalities and 100+ government websites.', '{"Deployed digital profile systems for 10+ municipalities including Pokhara Metropolitan City in 4 months with a 2-person team, serving 100,000+ citizens","Built a Survey Management System with custom ODK Fetcher processing 100,000+ survey responses with real-time analytics and live monitoring","Managed end-to-end DevOps pipelines (CI/CD, Docker, AWS EC2/S3, MinIO, Jenkins) ensuring 99.9% uptime for resource-constrained regions","Trained 300+ local officials and enumerators in digital tools for sustainable civic digitization"}', '{Next.js,NestJS,tRPC,PostgreSQL,MongoDB,Docker,AWS,MinIO,"ODK Collect/Central",Nginx}', '{"10+ municipal digital profiles deployed in 4 months with a 2-person team","100,000+ survey responses processed with real-time analytics","300+ local officials trained in digital tools"}', NULL, 0, '2026-08-16 12:22:04.126635+05:30', '2026-08-16 12:22:04.126635+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.experience (id, title, company, location, type, start_date, end_date, description, responsibilities, technologies, achievements, company_url, sort_order, created_at, updated_at) VALUES ('mandala-foods-consultant', 'AI & Automation Consultant', 'Mandala Foods', 'Remote, Nepal', 'job', '2026-01', NULL, 'Sole technical architect for a purpose-driven fruit upcycling startup, building AI and automation infrastructure from the ground up. Designed conversational AI systems and self-hosted production infrastructure to streamline operations and enable intelligent commerce.', '{"Designed and deployed Maya — an internal RAG-based knowledge chatbot for querying SOPs and operational documentation through natural language","Architected Maya Genie, a multi-channel conversational commerce platform (WhatsApp, Viber, Messenger) with a Go-based message orchestration gateway, LangChain RAG core, and Nepal payment integrations (Khalti, eSewa)","Built a public-facing product chatbot on a loosely coupled microservices architecture with independently deployable channels, orchestration, and cognitive core","Engineered a Go document sync service processing Vikunja task attachments (XLSX, CSV, DOCX) and auto-uploading to Google Drive to feed the n8n RAG embedding pipeline","Self-hosted and maintained a production VPS (Ubuntu 24.04, 12-core AMD EPYC, 48 GB RAM) running 10+ Dockerised services including n8n, Supabase, Traefik, Open WebUI, and a Claude API proxy","Built n8n automation workflows for document ingestion, Gemini-powered embedding pipelines, operational reporting, and industry news digests"}', '{Go,Python,LangChain,n8n,Docker,"Supabase (pgvector)","Anthropic Claude API",Redis,"RAG Architecture",Microservices,Traefik,"Open WebUI"}', '{"Maya Genie submitted to the AI by HER: Global Impact Challenge","10+ Dockerised production services self-hosted on a single VPS with full observability","Multi-channel commerce platform spanning WhatsApp, Viber, and Messenger"}', NULL, 0, '2026-08-16 12:22:04.725912+05:30', '2026-08-16 12:22:04.725912+05:30') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.experience_sub_roles (id, experience_id, title, company, start_date, end_date, description, responsibilities, technologies, achievements, sort_order) VALUES ('5211214f-96ce-4f83-b715-c1bc6fd96328', 'isrc-ninja-combined', 'Tech Lead', 'Ninja Infosys', '2025-02', '2026-02', 'Led technical architecture for Digital e-Palika and the Integrated Content Management System — a distributed, event-driven microservices platform powering national-scale governance infrastructure.', '{"Led technical architecture for Digital e-Palika platform serving 50+ municipalities, streamlining citizen services, revenue collection, and grievance handling","Architected the ICMS powering 100+ government websites nationwide on a distributed, event-driven microservices architecture built for high availability","Coordinated cross-functional teams to deliver governance solutions while maintaining scalability, resilience, and security across containerised deployments"}', '{Next.js,NestJS,Kafka,Kubernetes,PostgreSQL,Docker,Redis,CI/CD}', '{"100+ government websites powered by the ICMS platform","Digital e-Palika platform serving 50+ municipalities"}', 0) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.posts (id, type, slug, title, excerpt, content_markdown, cover_image_url, tags, status, published_at, created_at, updated_at) VALUES ('d0ef1635-7ac4-4453-a964-6bb73cdb02ec', 'learning-log', 'building-jlox-tree-walk-interpreter', 'Building jlox - A Tree-Walk Interpreter in Java', 'Built a complete interpreter for the Lox programming language from scratch in Java, covering every phase from scanning to closures and static variable resolution.', 'Worked through Part I of Robert Nystrom''s *Crafting Interpreters*, building jlox by hand in Java with IntelliSense disabled — every line typed, every mechanism traced until it stopped being mysterious.

## The Pipeline

A **Scanner** converts raw source text into tokens using a two-pointer approach and maximal munch. A **Parser** uses recursive descent to build an abstract syntax tree, with operator precedence encoded directly into the grammar''s rule hierarchy — lower-precedence rules delegating to higher-precedence ones, so the tree''s shape enforces evaluation order structurally rather than through any explicit precedence-checking logic.

## The Visitor Pattern

The **Interpreter** walks that tree using the Visitor pattern — a dispatch mechanism where each node type routes to the correct evaluation method through two stages: runtime polymorphism picks which `accept()` runs, and that method makes a fixed compile-time call to the right visit method on the Interpreter. The same pattern drives three completely separate tree walks: the Interpreter evaluates, the AstPrinter prints structure, and the Resolver performs static analysis.

## Environments and Scope

Variables live in a parent-chained **Environment** structure — a linked list of hash maps where each scope points outward to its enclosing one. Lookup walks outward until the variable is found or the chain ends. Block scope is managed by `executeBlock`, which saves the current environment, switches to a new inner one, and restores the original in a `finally` block — guaranteeing cleanup even on errors.

## Functions and Closures

Functions are first-class values. Each function declaration creates a `LoxFunction` object capturing the environment active at definition time as its closure. Every call creates a fresh environment whose parent is that captured closure — not the current environment. This single distinction is the entire closure mechanism:

```java
new Environment(closure)      // function — parent is defining scope
new Environment(environment)  // block — parent is current scope
```

The `Return` statement unwinds the call stack via a Java exception, caught only in `LoxFunction.call()` — the same exception-as-control-flow trick used for panic-mode error recovery in the Parser.

## The Resolver

The **Resolver** exists because closures alone are not enough. Capturing an environment object is insufficient when that object is mutable — a variable declared after a function definition can contaminate the function''s closure at runtime, causing it to see a binding that did not exist when the function was written.

The Resolver fixes this by walking the AST once before interpretation, computing for every variable reference exactly how many scope hops up it lives, and storing those distances in a hash map. The Interpreter then jumps directly to the right scope instead of walking dynamically — making later mutations to intermediate scopes structurally invisible.

## What''s Next

jlox is complete and correct. The same language gets reimplemented next as **clox** — a bytecode virtual machine written in C, where everything Java provided for free (garbage collection, object identity, dynamic arrays, hash tables) gets built from scratch, and the AST disappears entirely in favor of flat bytecode executed by a stack-based VM.', NULL, '{crafting-interpreters,compilers,interpreters,java,lox,ast,parsing,lexing,tree-walk-interpreter,visitor-pattern,closures,lexical-scoping,recursive-descent,programming-languages}', 'published', '2026-08-16 13:09:39.092+05:30', '2026-08-16 13:08:59.435847+05:30', '2026-08-16 13:15:58.309+05:30') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.profile (id, name, tagline, bio, email, phone, location, linkedin_url, github_url, twitter_url, youtube_url, instagram_url, scholar_url, orcid_url, website_url, avatar_url, resume_url, languages, academic_skills, updated_at) VALUES (1, 'Sarbagya Gho Shrestha', 'Engineer', 'Engineer who builds with purpose. I’m drawn to technology that connects people with services, automates meaningful work, and scales what matters, from governance platforms serving thousands of citizens to the first intelligent system at a startup. Comfortable working across the stack, from embedded hardware to distributed systems. Always learning, always building, always shipping.', 'sarbagyaghoshrestha@gmail.com', '+977 9823833365', 'Kathmandu, Nepal', 'https://linkedin.com/in/sarbagyashrestha', 'https://github.com/sarbagyag', NULL, 'https://www.youtube.com/@Sarbagya42', 'https://www.instagram.com/sarbu.wav', NULL, NULL, 'https://sarbagya.vercel.app', NULL, NULL, '[{"name": "English", "level": "Fluent (Proficient)"}, {"name": "Nepali", "level": "Native"}, {"name": "Newari", "level": "Native"}, {"name": "Hindi", "level": "Intermediate"}]', '{"Research Design & Methodology","Technical Writing","Data Analysis & Visualization","Literature Review","Experimental Design","Performance Analysis","Mathematical Modeling","Scientific Programming","Presentation & Communication","Collaborative Research"}', '2026-08-16 13:00:41.946+05:30') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('8bit-breadboard-computer', '8-bit Breadboard Computer (Ben Eater Inspired)', 'Built a complete 8-bit computer from scratch on breadboards inspired by Ben Eater''s design. 6th semester minor project at IOE Pulchowk Campus featuring custom-built 128-bit RAM due to IC unavailability.', 'Designed and constructed a fully functional 8-bit computer from the ground up using discrete logic ICs, inspired by Ben Eater''s architecture. As BEI students passionate about the intricate dance between hardware and software, Rohit Joshi, Yugal Pariyar, and I delved deep into computer architecture, building every component manually on breadboards. Faced with IC unavailability challenges, we innovatively created a homemade 128-bit RAM module, demonstrating our problem-solving abilities and determination. The project encompasses the complete architecture: ALU, control unit, registers, program counter, instruction decoder, clock module, and output display. This hardware-focused project exemplifies our passion for deep understanding of technology from first principles.', '{"Digital Logic","Computer Architecture","74-series Logic ICs","Breadboard Design","Hardware Engineering","ALU Design","Control Unit","Custom RAM"}', NULL, 'https://www.linkedin.com/feed/update/urn:li:activity:7199849262543749120/', NULL, NULL, true, 'systems', '2024-01', '2024-05', 'completed', 'Deep understanding of computer architecture from first principles', '{"Custom 128-bit RAM module","Complete 8-bit CPU implementation","Hardware-only design","3-person team achievement"}', 0, '2026-08-16 12:22:08.009679+05:30', '2026-08-16 12:22:08.009679+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('maya-genie', 'Maya Genie - AI Conversational Commerce Platform', 'Developing an intelligent nutrition assistance chatbot for Nepali market using RAG architecture. Enables customers to receive personalized nutrition recommendations and place orders through natural language.', 'Architecting Maya Genie, an AI-powered conversational commerce platform for Mandala Foods. The system uses Retrieval Augmented Generation (RAG) to provide context-aware nutrition guidance by integrating product catalog knowledge with AI inference. Customers can interact naturally to get personalized recommendations based on their health goals and dietary preferences, then seamlessly place orders through the conversation. Building scalable infrastructure for production deployment with vector databases for semantic search and efficient retrieval.', '{"RAG Architecture","Vector Databases","Conversational AI",NLP,Python,LangChain,PostgreSQL,Docker}', NULL, NULL, NULL, NULL, true, 'systems', '2024-08', NULL, 'ongoing', 'Enabling conversational commerce for nutrition-focused e-commerce in Nepal', '{"RAG-powered nutrition recommendations","Natural language order placement","Product catalog knowledge integration","Localized for Nepali market"}', 0, '2026-08-16 12:22:06.821428+05:30', '2026-08-16 12:22:06.821428+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('municipal-digital-profiles', 'Municipal Digital Profile Platform', 'Architected and deployed comprehensive digital profile systems for 10+ municipalities across Nepal, including Pokhara Metropolitan City. Built end-to-end platform transforming civic data into accessible, analytics-ready systems for local governance.', 'Led the design and implementation of digital profile platforms for over 10 municipalities in just 4 months with a 2-person team (Sarbagya & Trilochan Bhusal). Built complete full-stack systems featuring real-time data visualization, interactive dashboards, and citizen information portals. The platform integrates field data collection (ODK), automated data processing pipelines, and responsive web interfaces serving thousands of citizens. Deployed on scalable cloud infrastructure with CI/CD pipelines ensuring 99.9% uptime.', '{Next.js,NestJS,tRPC,PostgreSQL,TypeScript,Docker,Vercel,"ODK Central","Data Visualization","Responsive Design"}', NULL, 'https://pokhara.digprofile.com/en', NULL, NULL, true, 'systems', '2024-09', '2026-01', 'completed', 'Digitized 10+ municipalities, serving 100,000+ citizens', '{"10+ municipalities digitized in 4 months","2-person team achievement","100,000+ citizen records processed","99.9% platform uptime"}', 0, '2026-08-16 12:22:08.305725+05:30', '2026-08-16 12:22:08.305725+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('survey-management-system', 'Survey Management System (SMS)', 'Full-scale web platform for live monitoring, analytics, and visualization of municipal field surveys. Real-time dashboards enabling data-driven decisions for local administrations before survey completion.', 'Engineered a comprehensive Survey Management System integrating field data collection with cloud-based analytics. Built custom ODK Fetcher (NestJS-based parser) to automate data flow from ODK Collect mobile app to centralized PostgreSQL database. Created real-time dashboards using Next.js and tRPC showing live survey progress, building counts, demographic analytics, and geographic visualizations. Enabled local governments to monitor enumeration teams, track survey completion rates, and identify data quality issues in real-time. System processed 100,000+ survey responses across multiple municipalities.', '{Next.js,NestJS,tRPC,PostgreSQL,TypeScript,"ODK Collect","ODK Central","Data Visualization","Real-time Analytics",Chart.js,Docker}', NULL, 'https://duduwa-admin.vercel.app/', NULL, NULL, true, 'systems', '2024-09', '2026-01', 'completed', 'Enabled real-time field survey monitoring for 10+ municipalities', '{"100,000+ survey responses processed","Real-time monitoring for 10+ municipalities","Custom ODK integration pipeline","Live analytics dashboards"}', 0, '2026-08-16 12:22:08.607839+05:30', '2026-08-16 12:22:08.607839+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('vikunja-task-tracking', 'Vikunja Task Tracking System', 'Deployed and customized Vikunja as an internal task tracking and project management system for Mandala Foods. Configured production infrastructure with monitoring and data acquisition capabilities.', 'Implemented Vikunja as the internal task tracking and project management solution for Mandala Foods operations. Configured production-grade infrastructure including Docker containerization, Traefik reverse proxy for traffic management and SSL termination, and PostgreSQL database backend. Extended the system with custom integrations for fruit processing operations data acquisition and monitoring. Set up automated backups, logging, and DNS configuration for reliable production deployment.', '{Vikunja,Docker,Traefik,PostgreSQL,Redis,"Linux Administration",SSL/TLS,"DNS Management"}', NULL, NULL, NULL, NULL, true, 'systems', '2026-01', NULL, 'completed', 'Streamlined internal operations and project management for food tech startup', '{"Production-grade infrastructure","Traefik reverse proxy setup","Automated SSL management","Custom data acquisition integrations"}', 0, '2026-08-16 12:22:07.420277+05:30', '2026-08-16 12:22:07.420277+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('eshasan', 'eShasan: The OS for Digital Governance', 'The comprehensive digital ecosystem driving the modernization of Nepal''s public sector. A Multi-Tenant Digital Governance Platform unifying internal office automation, public service delivery, and citizen engagement.', 'Architected by Ninja Infosys, eShasan represents the cutting edge of GovTech engineering. It transforms complex bureaucratic processes into a streamlined, reactive digital experience using a Cloud-Native Microservices Architecture. The platform integrates Office Automation (Darta Chalani) with a robust Integrated Content Management System (ICMS), breaking down administrative silos. Features a modular Microfrontend architecture (Module Federation), polyglot backend services (Go, NestJS), and event-driven consistency via Apache Kafka. Containerized on Docker and orchestrated via Kubernetes for national-scale resilience.', '{"Microservices (Go)","Module Federation",Docker,React,Postgres,Traefik,"Ory Kratos, Oathkeeper",Kafka,Kubernetes}', NULL, NULL, NULL, NULL, true, 'systems', '2026-01', NULL, 'ongoing', 'Future-proof digital infrastructure for national-scale governance', '{"Multi-Tenant Architecture","Unified Command & Control (C2)","Digital Office Automation","100+ Government Portals"}', 0, '2026-08-16 12:22:07.713279+05:30', '2026-08-16 12:22:07.713279+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('mandala-internal-chatbot', 'Mandala Foods Internal AI Chatbot', 'Built an internal AI assistant for Mandala Foods operations using n8n automation and RAG-based decision systems. Streamlines internal queries, SOPs, and operational knowledge access.', 'Developed an internal AI chatbot for Mandala Foods to enhance team productivity and operational efficiency. The system leverages n8n workflow automation with RAG-based architecture to provide instant access to company SOPs, policies, and operational knowledge. Integrated with multiple business systems including CRM, inventory, and customer support platforms. Built automated data pipelines for business intelligence and reporting. Deployed on production infrastructure with Docker containerization.', '{"n8n Automation","RAG Architecture",Docker,PostgreSQL,"API Integrations","Workflow Automation"}', NULL, NULL, NULL, NULL, true, 'systems', '2026-01', NULL, 'completed', 'Reduced manual operational overhead through AI-powered internal assistance', '{"RAG-based knowledge retrieval","Multi-system integrations","Automated business workflows","Production Docker deployment"}', 0, '2026-08-16 12:22:07.122618+05:30', '2026-08-16 12:22:07.122618+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES ('icms-platform', 'Integrated Content Management System (ICMS)', 'Enterprise-scale CMS platform powering 100+ government websites across Nepal. Designed and engineered at Ninja Infosys for unified digital governance at national scale.', 'Architected and led development of ICMS, a comprehensive content management system now serving 100+ government institutions across Nepal. The platform provides unified website management, content publishing workflows, document management, citizen service portals, and analytics dashboards. Built with modern tech stack incorporating Kafka for event streaming, Kubernetes for orchestration, and microservices architecture for scalability. Enables municipalities and government agencies to maintain professional web presence with minimal technical expertise while ensuring security, compliance, and performance at scale.', '{Next.js,NestJS,Kafka,Kubernetes,PostgreSQL,Docker,Microservices,TypeScript,Redis,CI/CD}', NULL, 'http://sddodang.lumbini.gov.np/ne', NULL, NULL, true, 'systems', '2026-06', NULL, 'completed', 'Powering 100+ government websites nationwide', '{"100+ government sites live","National-scale deployment","Microservices architecture","Event-driven with Kafka"}', 0, '2026-08-16 12:22:08.909072+05:30', '2026-08-16 12:22:08.909072+05:30') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.skills (id, category, skills, proficiency, sort_order) VALUES ('51634d05-2608-436f-a666-b25fc0ad15d9', 'Programming Languages', '{TypeScript/JavaScript,Python,C/C++,Golang,SQL,"Shell Scripting"}', 'advanced', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.skills (id, category, skills, proficiency, sort_order) VALUES ('7de0176d-4050-49d5-a0fc-e03864a9d01d', 'Frontend Development', '{"Microfrontend (MFE)","Module Federation",Webpack,Next.js,React.js,Redux.js,HTML5,"CSS/Tailwind CSS","Responsive Design",UI/UX}', 'advanced', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.skills (id, category, skills, proficiency, sort_order) VALUES ('68b5758d-7d34-408a-a333-b2c8d86d872c', 'Backend Development', '{Go,Microservices,NestJS,Express.js,tRPC,Django,"Django REST Framework",Node.js,"API Design"}', 'advanced', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.skills (id, category, skills, proficiency, sort_order) VALUES ('389e7851-8f29-487f-a9e3-5cb6daa5c8b6', 'Databases & Data', '{PostgreSQL,MongoDB,Redis,SQL,"Data Modeling","ODK Collect","ODK Central","Data Visualization"}', 'advanced', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.skills (id, category, skills, proficiency, sort_order) VALUES ('c65ecae0-155c-4da6-bc22-8bbfea6c6726', 'DevOps & Cloud', '{Docker,Kubernetes,Jenkins,Kafka,"AWS (EC2, S3, Lambda)",CI/CD,Nginx,PM2,Coolify}', 'advanced', 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.skills (id, category, skills, proficiency, sort_order) VALUES ('7298e9cd-a69f-4ae5-851b-31c8e261fd74', 'AI & Embedded Systems', '{"Machine Learning","Deep Learning",TensorFlow,PyTorch,"Embedded Systems",UAVs,Avionics,IoT}', 'intermediate', 5) ON CONFLICT (id) DO NOTHING;

-- +goose Down
DELETE FROM experience_sub_roles WHERE id = '5211214f-96ce-4f83-b715-c1bc6fd96328';
DELETE FROM posts WHERE id = 'd0ef1635-7ac4-4453-a964-6bb73cdb02ec';
DELETE FROM projects WHERE id IN (
    'maya-genie', 'mandala-internal-chatbot', 'vikunja-task-tracking', 'eshasan',
    '8bit-breadboard-computer', 'municipal-digital-profiles', 'survey-management-system',
    'icms-platform'
);
DELETE FROM experience WHERE id IN (
    'isrc-ninja-combined', 'mandala-foods-consultant', 'ibtidaa-fullstack', 'ieee-chair',
    'ieee-creative', 'pulchowk-music', 'pointzeroo-frontend', 'ryc-global-officer'
);
DELETE FROM education WHERE id IN ('ioe-bachelor', 'sos-plus2');
DELETE FROM skills WHERE id IN (
    '51634d05-2608-436f-a666-b25fc0ad15d9', '7de0176d-4050-49d5-a0fc-e03864a9d01d',
    '68b5758d-7d34-408a-a333-b2c8d86d872c', '389e7851-8f29-487f-a9e3-5cb6daa5c8b6',
    'c65ecae0-155c-4da6-bc22-8bbfea6c6726', '7298e9cd-a69f-4ae5-851b-31c8e261fd74'
);
DELETE FROM profile WHERE id = 1;
