-- Seeds 9 new portfolio projects (major project, kernel, VM, embedded, and
-- web work) sourced from the resume/CV and project reports. Two are
-- "confidence: medium" (esp32-gesture-robot-car, async-job-board,
-- einding-productivity-pwa) — sourced from informal working notes rather
-- than the resume, so their dates/status/links should be double-checked
-- against reality and corrected via /admin if they've drifted.
--
-- ON CONFLICT DO NOTHING so this is safe to leave in place even if these
-- rows get hand-edited via /admin afterwards (matches 00002's pattern).
--
-- +goose Up
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('narration-ai-nepali-tts', 'Narration AI for Low-Resource Languages (Nepali)', 'Bachelor''s major project building a Nepali text-to-speech browser extension that narrates web news in real time, powered by a fine-tuned Tacotron2 model with a DeepGAN vocoder.', 'As my final-year major project at IOE Pulchowk Campus, I worked with Mausam Kumar Sah, Rohit Joshi, and Yugal Pariyar — under the supervision of Dr. Arun Kumar Timalsina and in collaboration with Prixa Technologies — to tackle a real gap in Nepali-language accessibility: the near-total absence of natural-sounding text-to-speech tools for a low-resource language spoken by tens of millions of people. We built a browser extension that scrapes Nepali text directly from news sites, chunks and preprocesses it, and streams it to a backend TTS pipeline built around a Tacotron2 spectrogram model paired with a DeepGAN vocoder for waveform synthesis. We trained the model on a mix of the OpenSLR Nepali dataset and our own self-recorded speech, pretraining on close to 2,000 sentences before fine-tuning for our target voice. In blind evaluation by 19 volunteers, the system scored a Mean Opinion Score of 3.91 out of 5 for naturalness — a strong result for a language with so little existing speech data to build on.', '{"Python","PyTorch","Tacotron2","DeepGAN","Django","Web Extension","ffmpeg","Google Colab"}', NULL, NULL, NULL, NULL, false, 'ai', '2024', '2025', 'completed', 'Bringing natural-sounding speech synthesis to a language technology has largely left behind.', '{"Tacotron2 + DeepGAN neural TTS pipeline fine-tuned for Nepali","Browser extension for real-time in-browser news narration","Mean Opinion Score of 3.91/5 from 19 volunteer evaluators","Custom-recorded + OpenSLR dataset training pipeline"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('zorbaos-kernel', 'zorbaOS: A Multithreaded 32-bit x86 Operating System Kernel', 'A multithreaded 32-bit x86 operating system kernel built from scratch — a custom bootloader, page-based virtual memory, a FAT16 virtual file system, and a preemptive scheduler.', 'zorbaOS is my from-scratch dive into operating systems at the lowest level. I wrote a custom x86 bootloader in assembly to handle real-mode initialization and the transition into 32-bit Protected Mode with hand-built GDT and IDT structures, then layered page-based virtual memory on top with a custom malloc/free heap allocator for process isolation. On top of that sits a Linux-inspired Virtual File System abstraction backed by a FAT16 driver, a cooperative/preemptive multitasking scheduler, and an ELF binary loader that runs user-space programs across Ring 0/Ring 3 privilege boundaries. Keyboard and PIC interrupt drivers feed into an interactive command-line shell so the whole thing is actually usable, not just theoretical.', '{"x86 Assembly","C","Bootloader Development","Protected Mode","Paging","Virtual Memory","VFS","FAT16","Multitasking","ELF Loader"}', 'https://github.com/sarbagyag/zorbaOS-kernel-dev', NULL, NULL, NULL, false, 'systems', '2026-07', NULL, 'ongoing', 'Understanding an operating system by building every layer of it by hand.', '{"Custom x86 bootloader and Protected Mode transition (GDT/IDT)","Page-based virtual memory with a custom heap allocator","Linux-inspired VFS with a FAT16 file system driver","Preemptive scheduler and ELF loader for Ring 0/Ring 3 execution"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('gholang-bytecode-vm', 'ghoLang: A Custom Bytecode Virtual Machine & Interpreter', 'A custom bytecode virtual machine and interpreter written in C, with a hand-rolled Pratt parser, a tri-color garbage collector, and Lua-style closures.', 'ghoLang is a programming language runtime I built in C from the ground up. Source code goes through a hand-written single-pass Pratt parser that compiles it directly into dense bytecode chunks, handling operator precedence without any parser generator. That bytecode runs on a stack-based VM with call-frame tracking, dynamic constant pools, and O(1) string comparisons via interning and bitwise-AND hash probing. Memory is managed by a tri-color mark-and-sweep garbage collector with self-adjusting heap growth thresholds, and the language supports first-class Lua-style closures with heap-migrating upvalues alongside a class system with single inheritance and constant-time method dispatch. I''ve since expanded the runtime with string interpolation, iterable hash maps, and module resolution.', '{"C","Pratt Parsing","Bytecode Compilation","Virtual Machines","Garbage Collection","Closures","OOP Runtime Design"}', 'https://github.com/sarbagyag/gholang', NULL, 'https://gholang.dev', NULL, false, 'languages', '2026-06', NULL, 'ongoing', 'A language runtime built one virtual machine instruction at a time.', '{"Hand-written single-pass Pratt parser compiling to bytecode","Stack-based VM with call frames and string interning","Tri-color mark-and-sweep garbage collector","Lua-style closures and a class system with single inheritance"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('stm32-self-balancing-robot', 'STM32-Based Self-Balancing Robot', 'Bare-metal STM32 firmware for a self-balancing robot, fusing IMU data with a complementary filter and closing the loop with PID motor control.', 'This project is my hands-on entry into embedded firmware development, writing bare-metal C for an STM32 (ARM Cortex-M) microcontroller using both HAL and Low-Layer drivers for direct control over peripheral registers, interrupts, and timing. I interfaced an MPU-6050 IMU over I2C to pull raw 6-axis accelerometer and gyroscope data, then implemented a real-time complementary filter to fuse the two into a stable tilt-angle estimate. Motor actuation runs through hardware PWM timers, with UART over USB-CDC providing live telemetry for debugging. I''m currently closing the loop: integrating an L298N dual H-bridge driver and tuning a discrete PID controller so the robot can actively balance itself.', '{"STM32","ARM Cortex-M","Embedded C","HAL/LL Drivers","I2C","PWM","UART/USB-CDC","MPU-6050","Complementary Filter","PID Control","L298N"}', 'https://github.com/sarbagyag/stm32-self-balancing-robot', NULL, 'https://docs.google.com/document/d/1Oy3eVqCZ4Oq2Mm3snnbUVZMDKufbxnAgHCzB2ccyURE/edit?usp=sharing', NULL, false, 'embedded', '2026-08', '2026-09', 'ongoing', 'Fusing sensor data into a stable balance, one control loop at a time.', '{"Bare-metal STM32 firmware with HAL/LL peripheral drivers","MPU-6050 sensor fusion via a real-time complementary filter","Hardware PWM motor control with UART/USB-CDC telemetry","PID closed-loop balancing control with an L298N driver (in progress)"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('zorlang-interpreter', 'zorLang: An AST Tree-Walk Interpreter & Domain-Specific Language', 'An AST tree-walk interpreter and domain-specific language built in Java, with a hand-written recursive descent parser and a full object-oriented runtime.', 'zorLang was my project for understanding interpreters from first principles, in Java. I wrote a hand-built recursive descent parser that scans, tokenizes, and parses source into a strongly typed Abstract Syntax Tree, then walk that tree with a hierarchical environment scoping model supporting nested blocks, dynamic typing, and lexical closures. Execution runs through the Visitor design pattern, keeping tree traversal cleanly separated from evaluation logic across control flow constructs like if/else, while, and for. On top of that sits an object-oriented runtime with initializer methods, instance properties, and dynamic method binding, backed by comprehensive lexical and runtime error reporting.', '{"Java","Recursive Descent Parsing","Abstract Syntax Trees","Visitor Pattern","Lexical Scoping","Interpreter Design"}', 'https://github.com/sarbagyag/zorLang', NULL, 'https://zor-lang.vercel.app/', NULL, false, 'languages', '2026-04', '2026-07', 'completed', 'Learning how languages work by writing one from the ground up.', '{"Hand-written recursive descent parser producing a typed AST","Hierarchical environment scoping with lexical closures","Visitor-pattern tree-walk execution engine","Full OOP runtime with initializers and dynamic method binding"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('tda2030-active-amplifier', 'TDA2030 2.1-Channel Active Amplifier & Analog Signal Processing System', 'A hand-designed 2.1-channel audio amplifier built to learn PCB design and analog filter theory — three TDA2030 power stages, an active crossover, and a full-wave split power supply.', 'I built this amplifier as a deliberate hands-on exercise in PCB design and analog signal processing, taking it from schematic to a finished, hand-soldered board. The design integrates three TDA2030 power amplifier stages, a 2nd-order Sallen-Key Butterworth active crossover at 120 Hz splitting audio into satellite and subwoofer bands, and a full-wave split power supply off a center-tapped transformer with local decoupling and a shared heatsink for thermal management. I did the schematic capture and board layout myself in KiCad, then added volume and bass trim potentiometers as a practical improvement over the base reference design. I also used the analog filter''s transfer functions and bilinear transforms to model the equivalent digital IIR biquad filters, as a bridge toward porting the same crossover logic onto a microcontroller.', '{"KiCad","PCB Design","Analog Filter Design","TDA2030","Op-Amps","Power Electronics","DSP Fundamentals"}', NULL, NULL, 'https://docs.google.com/document/d/11Hutb2XuUZJ_NZS31ArYTHtnT9LSCabwxx69DxiAypk/edit?tab=t.0#heading=h.oj1l666atdkh', NULL, false, 'hardware', '2026-09', '2026-09', 'completed', 'Learning analog filter theory by building the circuit that needs it.', '{"Full schematic capture and PCB layout in KiCad, hand-soldered","2nd-order Sallen-Key Butterworth active crossover (120 Hz)","Full-wave split power supply with thermal management","Analog-to-digital IIR biquad filter modeling for MCU porting"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

-- confidence: medium — sourced from informal working notes, not the resume; verify dates/status/links before treating as final
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('esp32-gesture-robot-car', 'ESP32 Gesture-Controlled Robot Car', 'A handheld gyroscope remote wirelessly driving a 4WD robot car over ESP-NOW.', 'This project pairs a handheld remote with a separate car unit, both built on ESP32s. The remote reads tilt data from an MPU6050 gyroscope and streams it wirelessly over ESP-NOW to the car unit, which translates that tilt into motor commands. The car itself is a 4WD build — four TT gear motors wired in left/right pairs on a plywood strip chassis — powered by two 18650 Li-ion cells with onboard USB charging and a slide power switch. It runs on ESP-IDF and FreeRTOS rather than the Arduino framework, keeping gesture-sensing and the wireless link running as proper concurrent tasks.', '{"ESP32","ESP-IDF","FreeRTOS","ESP-NOW","MPU6050","Motor Control"}', NULL, NULL, NULL, NULL, false, 'embedded', '2026', '2026', 'completed', 'Controlling a robot with a tilt of the wrist.', '{"Handheld MPU6050 gyroscope remote","Wireless ESP-NOW link between remote and car unit","4WD chassis with independent left/right motor control","Li-ion powered with onboard USB charging"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

-- confidence: medium — sourced from informal working notes, not the resume; framed as a learning exercise, verify current status before treating as final
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('async-job-board', 'Async Job Board', 'A full-stack job board built by hand to go deep on Go and TypeScript fundamentals — a worker-pool backend and a class-based frontend with no frameworks.', 'I built this job board application from scratch as a deliberate learning exercise, writing every line by hand in Neovim rather than scaffolding it with a framework. The backend is Go, built around a worker pool for handling background jobs and talking to PostgreSQL through pgx. The frontend is TypeScript structured around plain object-oriented class patterns — an ApiClient for network calls, a JobStore for state, a JobPoller for real-time updates, and abstract View subclasses for rendering — instead of reaching for React or another framework.', '{"Go","PostgreSQL","pgx","TypeScript","OOP Frontend Architecture"}', NULL, NULL, NULL, NULL, false, 'web', '2026', NULL, 'ongoing', 'Going deep on Go and TypeScript by building everything by hand.', '{"Go backend built around a worker pool","PostgreSQL access via pgx, no ORM","Hand-written TypeScript frontend with OOP class architecture","No frameworks — every line written from scratch in Neovim"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

-- confidence: medium — sourced from a brief working-note mention only; verify scope/status and any live/repo link before treating as final
INSERT INTO public.projects (id, title, description, long_description, technologies, github_url, live_url, paper_url, image_url, featured, category, start_date, end_date, status, impact, metrics, sort_order, created_at, updated_at) VALUES
('einding-productivity-pwa', 'Einding: A Productivity Progressive Web App', 'A productivity progressive web app with a React/Vite frontend and a Go backend, self-hosted on a personal VPS.', 'Einding is a productivity app I built end-to-end, pairing a React and Vite frontend with a Go backend, deployed on my own VPS as an installable, offline-capable progressive web app.', '{"React","Vite","Go","PWA","VPS Deployment"}', NULL, NULL, NULL, NULL, false, 'web', '2026', '2026', 'completed', 'A productivity tool built and hosted end-to-end.', '{"React + Vite frontend","Go backend","Deployed as an installable, offline-capable PWA","Self-hosted on a personal VPS"}', 0, now(), now())
ON CONFLICT (id) DO NOTHING;

-- +goose Down
DELETE FROM public.projects WHERE id IN (
  'narration-ai-nepali-tts',
  'zorbaos-kernel',
  'gholang-bytecode-vm',
  'stm32-self-balancing-robot',
  'zorlang-interpreter',
  'tda2030-active-amplifier',
  'esp32-gesture-robot-car',
  'async-job-board',
  'einding-productivity-pwa'
);
